services:
  reto4:
    build: .
    container_name: escape_reto4
    restart: unless-stopped

    ports:
      - "2204:22"
    
    environment:
      - TZ=Europe/Madrid
      - SSH_USER=jugador
      - SSH_PASS=password
      - FLAG=sn1ff_secret
      - FTP_PASS=clave_secreta_ftp

    cap_add:
      - NET_ADMIN # Permite usar iptables dentro del contenedor
      - NET_RAW # Permite usar iptables dentro del contenedor

    mem_limit: 512m
    
    cpus: '0.5'

    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/22"]
      interval: 5s
      timeout: 3s
      retries: 6
      start_period: 10s
    
    networks:
      - red_ssh
      - red_interna

networks:
  red_ssh:
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: 172.100.7.0/24
  red_interna:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.100.8.0/24