FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    openssh-server \
    nmap \
    netcat-openbsd \
    curl \
    iptables \
    ftp \
    tcpdump \
    libcap2-bin \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /var/run/sshd
RUN echo 'PermitRootLogin no'         >> /etc/ssh/sshd_config
RUN echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config

COPY setup_jugador.sh /setup.sh
RUN chmod +x /setup.sh

EXPOSE 22
CMD ["/setup.sh"]